### PR TITLE
feat: change folder naming convention for jna compatible.

### PR DESCRIPTION
**Pull request by kidylee**
JNA, which is based on JNI, using conventions to eliminate boilerplate, so the rust function doesn't need take JNIEnv things as default parameters.

One of convention is that it will look up lib {os}-{aarch} folder from root of classpath. I was taking assumption that rust-maven-plugin is a universal plugin to compile Rust, not only JNI related, hence I submit this PR to support JNA.

### CODE REVIEW

**Comment by amunra** [comment]
Hi,

I've briefly looked at the submission.

Could you create a companion issue detailing the problem you're having and what the code changes you're proposing would solve?

I'm not familiar with JNA, so I'd like to understand why a different naming convention would help here.

You would also need to sign the contributor agreement.

Thanks,
Adam

**Comment by kidylee** [comment]
> Hi,
> 
> I've briefly looked at the submission.
> 
> Could you create a companion issue detailing the problem you're having and what the code changes you're proposing would solve?
> 
> I'm not familiar with JNA, so I'd like to understand why a different naming convention would help here.
> 
> You would also need to sign the contributor agreement.
> 
> Thanks, Adam

Thanks Adam, I have update the description of this PR, do you need me to create a separate Issue for this?

**Comment by amunra** [comment]
Yes, your submission is certainly relevant to the project and will be useful to others too. Let's try and get it merged. 

Before I accept the PR, I need to fully understand it or I'll have trouble reviewing it. The PR also needs better docs and tests.

At the moment I don't quite have enough context for this and I need a few more pointers. 

Can you provide a link that documents or implements the directory naming convention and add it in comments to the code? I'm assuming this would be a piece of code in the JNA project you're trying to match. 

Can you provide a usage example with a rust binary compiled for JNA? Does the JNA dynamic library get included in the JAR? 
What method in JNA would one ultimately use to load the compiled code? I'm assuming this would not be using the jar-jna lib in this project, but something else that requires that naming convention.

I'll then help you with the docs.

**Comment by amunra** [comment]
Hi I'm back from holiday.
Sorry for taking so long to reply.

I'm happy to accept the PR in what it wants to achieve, but not with its implementation. It requires more work before it's of a sufficient quality standard:
* I don't think that adding a dependency between `jar-jni` and `jna` would be a good idea, but I think it would be fair to copy the existing implementation from the JNA project here (https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Platform.java), whilst preserving its copyright notice as-is, but changing its package name from `package com.sun.jna;` to `package io.questdb.jar.jni;` to avoid collisions. The jna project is dual-licensed where one of the licenses it's released under is the Apache 2.0 license which would allow us to do this (this is the same license as `rust-maven-plugin`).
  * We should then have tests that assert that the two implementations match.
  * This would ensure that using JNA is and remains compatible across multiple platforms today and in the future.
* It really should have a new jna example as part of it, or there's not much point introducing the breaking change.
  * I would suggest renaming `rust-maven-example` to `rust-maven-jni-example` and introducing a new `rust-maven-jna-example`. The example should also use the latest version of JNA 5.x, not JNA 4.x.
  * Once it's in, I'm happy to write the docs for it.

**Comment by amunra** [comment]
I've also raised an issue with the JNA project to see if they'd be willing to ship the naming convention logic into a separate .jar. See: https://github.com/java-native-access/jna/issues/1515

**Comment by amunra** [comment]
The JNA team would not be willing to split up their library into a smaller dependency that would be suitable to consume from the `jar-jni` project. As such I think copying and pasting the implementation (as per my original suggestion) is still the way to go.

**Comment by amunra** [comment]
I have taken your code and tweaked it a bit.
See: https://github.com/questdb/rust-maven-plugin/pull/34

I'm closing this PR in favour of that one.

**Comment by amunra** [comment]
PS: Sorry for taking so long to get around to this!

**Pull request closed without merging**
